### ISSUE TITLE
what is the meaning of distributed system

### ISSUE THREAD

**Issue by zhangli-abcd** [QiufangMa/control-schedule-framework#3]
In the introductin, you write " * Ensuring synchronization of scheduled resources across distributed systems", so does the distributed system mean there are several controllers or no controller?

**Comment by danielkinguk** [comment]
Thinking further, it may be more realistic that single controller entity will have multiple logical controller instances, rather than separate controllers. But, I have seen a controller working alongside an EMS or NMS in the same network, should we consider this a scenario. Or, we can have an assumptions section that specifies implementing scheduling in the network should be done via a single point of control, reducing the risk of conflicting changes.

We could consider a schedule locking mechanism where only one EMS or Controller can make schedule requests to a specific network node at a time, to prevent simultaneous conflicting changes - this could include a Timeout and Deadlock. 

Ideally, we want a realistic scenario but not too complicated to actually solve with the current YANG we have.

**Comment by QiufangMa** [comment]
> Thinking further, it may be more realistic that single controller entity will have multiple logical controller instances, rather than separate controllers. But, I have seen a controller working alongside an EMS or NMS in the same network, should we consider this a scenario. Or, we can have an assumptions section that specifies implementing scheduling in the network should be done via a single point of control, reducing the risk of conflicting changes.
> 
> We could consider a schedule locking mechanism where only one EMS or Controller can make schedule requests to a specific network node at a time, to prevent simultaneous conflicting changes - this could include a Timeout and Deadlock.
> 
> Ideally, we want a realistic scenario but not too complicated to actually solve with the current YANG we have.

I think it makes sense to me if there is more than one schedule service requester, conflict already might happen under the management of one single controller, multiple clients just worsen the cases (but i think it is still possible and makes sense). NETCONF already has the lock mechanism to allow only one client to edit the configuration at a time, I guess we can add some text to cover this cases. I will propose some later.

**Comment by QiufangMa** [comment]
See https://github.com/QiufangMa/control-schedule-framework/pull/10/
